# This file was generated by GoReleaser. DO NOT EDIT.
cask "riptides-cli" do
  version "0.5.16-rc1"

  on_macos do
    on_intel do
      sha256 "6fc3863d44aa33e5a55e9006c1be071c91131a5988dbca4cb433b1b2b137056d"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4e884d68a48f59aeef68d16a1ec5c96bf4d25c6c2732d2a32271eed85a573f1"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0eeb856cebbda7b5a388c45903ab72b551e9652b5fc7c0d8bada4bc8b755df0e"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ee160eafe9b249c14d8a2823ca083838fb71655b0d1e921f59e2bfcde5b9053"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "riptides-cli"
  desc "Riptides CLI client"
  homepage "https://riptides.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "riptides-cli"

  # No zap stanza required

end
