# This file was generated by GoReleaser. DO NOT EDIT.
cask "riptides-cli" do
  version "0.5.16-rc2"

  on_macos do
    on_intel do
      sha256 "8338c31943fb9ec3b4dd0128510a614055326fc1aca333236b953d73d1bb6bd4"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/riptides-packages/daemon/"
    end
    on_arm do
      sha256 "5589add7b51fa2ce68cb96d8cac1b3a323a75b86730bbb9e268f125a1fe3c6bc"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/riptides-packages/daemon/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e327a4549fbd39f68b679d30a240b546143bd78f81f2458efb8c814b412ddd99"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/riptides-packages/daemon/"
    end
    on_arm do
      sha256 "9216bb5eda698025e06853bbc7c598fbd620519cc0383b0dd35c56c638bc0d42"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/riptides-packages/daemon/"
    end
  end

  name "riptides-cli"
  desc "Riptides CLI client"
  homepage "https://riptides.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "riptides-cli"

  postflight do
    system 'xattr', '-dr', 'com.apple.quarantine', "#{staged_path}/riptides-cli"
  end

  # No zap stanza required

end
