# This file was generated by GoReleaser. DO NOT EDIT.
cask "riptides-cli" do
  version "0.5.16-rc1"

  on_macos do
    on_intel do
      sha256 "047aedf19903a5eb77d4d849c70f285c625fc5551ddeaf7fd68d14f906c9685e"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "156ec320a5f851ed25f950d06673f1fcb1201a3b7dd1befa682c90aeeabd4479"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d255268fea7dc785c477bf077d2be0a4879bd1a6b356f6fe709003344f44a327"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0590ba5105ff686092e9765452deb068b31fb5d1265ce93ab612fa0e421264b7"
      url "https://github.com/riptides-packages/daemon/releases/download/v#{version}/daemon-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "riptides-cli"
  desc "Riptides CLI client"
  homepage "https://riptides.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "riptides-cli"

  # No zap stanza required

end
